#!/bin/bash

### BEGIN INIT INFO
# Provides:          Mirai-Dice
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Dice monitoring
# Description:       Start or stop the Mirai-Dice Client
### END INIT INFO

NAME="Mirai-Dice"
NAME_BIN="mcl.jar"
AutoShell_NAME_BIN="RestartService.sh"
Info_font_prefix="\033[32m" && Error_font_prefix="\033[31m" && Font_suffix="\033[0m"
if [[ -e "/usr/local/MiraiDice/mcl.jar" ]]; then
	BIN="/usr/local/MiraiDice/mcl.jar"
elif [[ -e "/usr/local/MiraiDice/mcl.jar" ]]; then
	BIN="/usr/local/MiraiDice/mcl.jar"
else
	echo -e "${Error_font_prefix}[错误]${Font_suffix} 核心文件($NAME_BIN)找不到 !" && exit 1
fi
RETVAL=0
time=$(date +"%Y%m%d%H%M%S")

check_running(){
	PID=$(pgrep -f "${NAME_BIN}")
	if [[ -n ${PID} ]]; then
		return 0
	else
		return 1
	fi
}

check_running_Autorestart(){
	A_PID=$(pgrep -f "${AutoShell_NAME_BIN}")
	if [[ -n ${A_PID} ]]; then
		return 0
	else
		return 1
	fi
}

do_start(){
	if check_running; then
	echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAME (PID ${PID}) 正在运行..." && exit 0
	else
		ulimit -n 51200 >/dev/null 2>&1
		nohup java -Dmirai.slider.captcha.supported -jar "$BIN" > /tmp/Mirai/Mirai_log_${time}.log 2>&1 &
		sleep 2s
		if check_running; then
			echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAME 启动成功 !"
		else
			echo -e "${Error_font_prefix}[错误]${Font_suffix} $NAME 启动失败 !"
		fi
	fi
}
do_startauto(){
	if check_running_Autorestart; then
	echo -e "${Info_font_prefix}[信息]${Font_suffix} 守护进程 (PID ${PID}) 正在运行..." && exit 0
	else
		ulimit -n 51200 >/dev/null 2>&1
      nohup /usr/local/MiraiDice/RestartService.sh 
		sleep 2s
		if check_running_Autorestart; then
			echo -e "${Info_font_prefix}[信息]${Font_suffix} 守护进程 启动成功 !"
		else
			echo -e "${Error_font_prefix}[错误]${Font_suffix} 守护进程 启动失败 !"
		fi
	fi
}
do_stop(){
	if check_running; then
		kill -9 "${PID}"
		RETVAL=$?
		if [[ $RETVAL -eq 0 ]]; then
			echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAME 停止成功 !"
		else
			echo -e "${Error_font_prefix}[错误]${Font_suffix}$NAME 停止失败 !"
		fi
	else
		echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAME 未运行 !"
		RETVAL=1
	fi
}
do_stopauto(){
	if check_running_Autorestart; then
		kill -9 "${A_PID}"
		sleep 2s
		if check_running_Autorestart; then
			echo -e "${Info_font_prefix}[信息]${Font_suffix} 守护进程 关闭失败 !"
		else
			echo -e "${Error_font_prefix}[错误]${Font_suffix} 守护进程 关闭成功 !"
		fi
	fi
}
do_status(){
	if check_running; then
		echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAME (PID ${PID}) 正在运行..."
	else
		echo -e "${Info_font_prefix}[信息]${Font_suffix} $NAME 未运行 !"
		RETVAL=1
	fi
}
do_restart(){
	do_stop
	do_start
}
do_restartauto(){
	do_stopauto
	do_startauto
}
case "$1" in
	start|stop|restart|status|startauto|stopauto|restartauto)
	do_"$1"
	;;
	*)
	echo "使用方法: $0 { start | stop | restart | status | startauto | stopauto | restartauto }"
	RETVAL=1
	;;
esac
exit $RETVAL